version: "3.8"
   
services:
    flask_web:
        container_name: web_kanal_service
        build: .
        command: ./run_web.sh
        volumes:
            - .:/usr/src/app
        ports:
            - "5000:5000"
        depends_on:
            - postgres

    postgres:
        container_name: db_kanal_service
        env_file: ./docker/.env-postgresql
        image: postgres
        environment:
            TZ: 'Asia/Yekaterinburg'
            PGTZ: 'Asia/Yekaterinburg'
        ports:
          - 32700:5432
        volumes:
            - pgdata:/var/lib/postgresql/data/
            - /etc/localtime:/etc/localtime:ro

    redis:
        container_name: redis_kanal_service
        image: redis:latest
        environment:
            TZ: 'Asia/Yekaterinburg'
        ports:
            - "32701:6379"

    celery_worker:
        container_name: celery_worker_kanal_service
        build: .
        image: celery:latest
        command:  ./run_celery_worker.sh
        volumes:
            - .:/usr/src/app
        env_file:
            - .env
        environment:
            - FLASK_APP=webapp
        depends_on:
            - redis
            - postgres

    celery_beat:
        container_name: celery_beat_kanal_service
        build:
            context: .
        image: celery:latest
        command: ./run_celery_beat.sh
        volumes:
            - .:/usr/src/app
        env_file:
            - .env
        environment:
            - FLASK_APP=webapp
        depends_on:
            - redis
            - postgres
    
    flower:
        container_name: flower_kanal_service
        build:
            context: .
        image: celery:latest
        command: ./run_flower.sh
        volumes:
            - .:/usr/src/app
        env_file:
            - .env
        environment:
            - FLASK_APP=webapp
        ports:
            - 5557:5555
        depends_on:
            - redis
            - postgres

volumes:
    pgdata:
